#spring:
#  profiles:
#    active: dev
#
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://demo-backend-db.civ6pe384nrx.ap-northeast-2.rds.amazonaws.com:3306
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect

spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common

# 공통으로 사용할 설정값

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://demo-backend-db.civ6pe384nrx.ap-northeast-2.rds.amazonaws.com:3306
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod